(deftheme default-davidt
  "David's theme")

(custom-theme-set-faces
 'default-davidt
 '(default ((t (:inherit nil :stipple nil :background "#012b36" :foreground "White" :inverse-video nil :box nil :strike-t*hrough nil :overline nil :underline nil :slant normal :weight normal :width normal :family "Menlo" :height 160))))
 '(cursor ((t (:background "Red"))))
 '(ediff-even-diff-A ((t (:background "#2aa198" :foreground "#fdf6e2"))))
 '(ediff-even-diff-Ancestor ((t (:background "grey70" :foreground "#fdf6e2"))))
 '(ediff-even-diff-B ((t (:background "#2aa198" :foreground "#fdf6e2"))))
 '(ediff-even-diff-C ((t (:background "#2aa198" :foreground "#fdf6e2"))))
 '(ediff-odd-diff-A ((t (:background "#268bd2" :foreground "#fdf6e2"))))
 '(ediff-odd-diff-B ((t (:background "#268bd2" :foreground "#fdf6e2"))))
 '(ediff-odd-diff-C ((t (:background "#268bd2" :foreground "#fdf6e2"))))
 '(font-lock-comment-face ((t (:foreground "SeaGreen1"))))
 '(font-lock-doc-face ((t (:foreground "#8d92a8"))))
 '(font-lock-function-name-face ((t (:foreground "#70b0ff"))))
 '(font-lock-keyword-face ((t (:foreground "#268bd2"))))
 '(font-lock-type-face ((t (:foreground "#859900"))))
 '(font-lock-warning-face ((nil (:foreground "#ff6666"))))
 '(highlight ((t (:background "BlueViolet" :foreground "Yellow"))))
 '(hl-line ((nil (:background "#01222c"))))
 '(isearch ((t (:background "DeepPink2" :foreground "Yellow" :weight bold))))
 '(js2-error-face ((t nil)) t)
 '(js2-function-param ((t (:foreground "#f3c1ff"))))
 '(js2-jsdoc-tag ((t (:foreground "#baacff"))))
 '(js2-jsdoc-type ((t (:foreground "#34d3fb"))))
 '(js2-jsdoc-value ((t (:foreground "gray85"))))
 '(js2-warning-face ((t nil)) t)
 '(lazy-highlight ((t (:background "SeaGreen4" :foreground "Yellow"))))
 '(region ((nil (:background "#464740"))))
 '(show-paren-match ((t (:background "DeepSkyBlue" :foreground "Yellow" :weight bold))))
 '(show-paren-mismatch ((t (:background "Red" :foreground "Yellow" :weight bold))))
 '(whitespace-trailing ((t (:background "red4" :foreground "yellow" :weight bold))))
 '(yas-field-highlight-face ((nil (:background "#333399"))))
 )

(provide-theme 'default-davidt)
